### ISSUE TITLE
Should we include an extra field 'appendix'

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/ADSfulltext#23]
Should we extract the appendix of the paper as a separate entity that would allow it to be indexed and searched by the users, or stick it on to the end of the full text?

**Comment by aaccomazzi** [comment]
I think we should just shove all of this in the body, given that the use cases for having this be a separate field are non-existent at this point and the complexity of doing so is non-negligible.

For the implementation, we should do our best to make sure that references are not included in what goes in &lt;body&gt; but otherwise grab other backmatter material.
