### ISSUE TITLE
Check text extraction for 2010ApJ...708.1321R

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/ADSfulltext#4]
Unicode sequences look different from old one.

**Comment by jonnybazookatone** [comment]
This is fixed for XML extraction. If it is seen again, open a new ticket. This will be closed on the next merge of my fork with master.

I've opened another issue #5 so that I will check that the PDF Extractor is doing what I expect with regards to UTF-8 encodings.

For future reference:
- Full text extracted from _any_ file is encoded in UTF-8
- meta.json files are encoded as ASCII, and contain _unicode literals_, i.e., '\u0000' within the relevant strings. Use the Python JSON library to deal with these files.

**Comment by jonnybazookatone** [comment]
Also, not to forget in the future, this was the most relevant source of information:

http://farmdev.com/talks/unicode/

**Comment by jonnybazookatone** [comment]
Fixed in #6
